No_dataset: 0
T: 4
TET: false
aa: rand-m11-n3
amp: true
batch_size: 128
cal_ratio_loss: true
connect_f: ADD
cos_lr_T: 320
crop_pct: null
data: /home/guodong/runhua/data
dataset_name: cifar100
epochs: 200
exp_name: sew34(from_cifar10_train)_cifar100_sgd_lr_1e-1_wd5e-4_300epoch_smoothing_0_mixup_0.1_T4_1_1_1_1_epoch_200_aa_rand-m11-n3
img_size: 224
lamb: 0.05
local_rank: 0
log_dir: log_out/log/sew34(from_cifar10_train)_cifar100_sgd_lr_1e-1_wd5e-4_300epoch_smoothing_0_mixup_0.1_1_1_1_1_epoch_200_aa_rand-m11-n3.txt
log_interval: 50
loss_ratio: null
lr: 0.1
lr_min: 0.0
means: 1.0
mixup: 0.1
model: sew_34
momentum: 0.9
num_classes: 10
num_gpu: 1
only_test: false
opt: sgd
output: /home/guodong/runhua/cifar_finetune/spe_snn_finetune_cifar/output
re_prob: 0.0
resume: /home/guodong/runhua/cifar_finetune/spe_snn_finetune_cifar/output/train/20231022-143814-sew34_cifar10_sgd_lr_1e-1_sm_0_wd5e-4_300epoch_T4/sew34_cifar10_sgd_lr_1e-1_sm_0_wd5e-4_300epoch_T4_299.pt
save_model_interval: 5
sched: cosine
seed: 1029
slice_len: 0
smoothing: 0.0
split_num: 5
template: .
time_ratio:
- 1.0
- 1.0
- 1.0
- 1.0
val_batch_size: 128
val_workers: 2
warmup: 0
weight_decay: 0.0005
workers: 2
zero_init_residual: true
